### ISSUE TITLE
Publish a tag

### ISSUE THREAD

**Issue by garronej** [Soremwar/deno_types#8]
Hi, 
[deno.land/x](https://deno.land/x) has changed, you must publish a tag and register a webhook.

Best regads

**Comment by Soremwar** [comment]
Hi,

This repository isn't a module that follows versioning as a whole codebase, but rather works as a mono-repo for type definitions.

If you wanna import them you can use Denopkg or raw GitHub urls alternatively.

**Comment by garronej** [comment]
It works for me thanks

**Comment by garronej** [comment]
I still think, for the sake of the visibility of this repo that a tag should be published.
Otherwise https://deno.land/x/types/react-dom/v16.13.1/react-dom.d.ts.

However good job with this initiative !
