### ISSUE TITLE
error: Import 'https://deno.land/x/types/react/v16.13.1/react.d.ts' failed: 404 Not Found

### ISSUE THREAD

**Issue by xcatliu** [Soremwar/deno_types#9]
```tsx
// @deno-types="https://deno.land/x/types/react/v16.13.1/react.d.ts""
import React from 'https://dev.jspm.io/react@16.13.1';
// @deno-types="https://deno.land/x/types/react-dom/v16.13.1/server.d.ts"
import ReactDOMServer from 'https://dev.jspm.io/react-dom@16.13.1/server.js';

console.log(ReactDOMServer.renderToString(<div />));
```

`https://deno.land/x/types/react/v16.13.1/react.d.ts` response 404 when exec `deno run test.tsx`

**Comment by xcatliu** [comment]
Related issue:
- https://github.com/xcatliu/pagic/issues/34
- https://github.com/xcatliu/pagic/issues/33

**Comment by xcatliu** [comment]
As @lucacasonato said:

> Sorry this was a bug on deno.land/x. It should be fixed now. Don't forget to relink the repository with deno.land/x if you have not done so after the recent update: https://deno.land/posts/registry2

Perhaps you need to follow the new registry step for deno.land/x

**Comment by quaos** [comment]
Still 404 not found today.

**Comment by Soremwar** [comment]
@xcatliu @quaos Sorry for the reply delay.

The repo was just updated with new instructions for use of the library. (More details on why deno registry was removed on #8 )

New import route goes as follows `https://denopkg.com/soremwar/deno_types/library/version/file.d.ts`
